// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx63Mw0FKY4kuIMXxks6eneRabuvl0rbs',
    appId: '1:983582489419:web:c7d022dc130a2dd31006ce',
    messagingSenderId: '983582489419',
    projectId: 'concertotheque',
    authDomain: 'concertotheque.firebaseapp.com',
    storageBucket: 'concertotheque.firebasestorage.app',
    measurementId: 'G-5H68THSY1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtq3G5WmZyvPZG2I1_rdmJSX9rO_BuLuw',
    appId: '1:983582489419:android:9bed2591728c13721006ce',
    messagingSenderId: '983582489419',
    projectId: 'concertotheque',
    storageBucket: 'concertotheque.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7uLoKwtTxhFh3s14a1S95P3CN1oVPazQ',
    appId: '1:983582489419:ios:31fd242362c790671006ce',
    messagingSenderId: '983582489419',
    projectId: 'concertotheque',
    storageBucket: 'concertotheque.firebasestorage.app',
    iosBundleId: 'com.example.concertothequeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7uLoKwtTxhFh3s14a1S95P3CN1oVPazQ',
    appId: '1:983582489419:ios:31fd242362c790671006ce',
    messagingSenderId: '983582489419',
    projectId: 'concertotheque',
    storageBucket: 'concertotheque.firebasestorage.app',
    iosBundleId: 'com.example.concertothequeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx63Mw0FKY4kuIMXxks6eneRabuvl0rbs',
    appId: '1:983582489419:web:384cf9d6ca940c541006ce',
    messagingSenderId: '983582489419',
    projectId: 'concertotheque',
    authDomain: 'concertotheque.firebaseapp.com',
    storageBucket: 'concertotheque.firebasestorage.app',
    measurementId: 'G-FRZFN3BNFD',
  );
}
